server: 
  port: 7005

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
            shareSecurityContext: true
# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        compression:
        request:
          enabled: true
        response:
          enabled: true
#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

spring: 
  application:
    name: demo-server
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 1

# spring security 配置
#security:
#  oauth2:
#    resource:
#      loadBalanced: true
#      token-info-uri: http://pig-auth/oauth/check_token