server: 
  port: 7002
logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000

spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/uaa/**
          filters:
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
#            # 验证码处理
#            - ValidateCodeGatewayFilter
#            # 前端密码解密
#            - PasswordDecoderFilter
        #系统管理模块
        - id: system-server
          uri: lb://system-server
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # demo 模块
        - id: demo-server
          uri: lb://demo-server
          predicates:
            - Path=/ds/**
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

security:
  encode:
    # 前端密码密钥，必须16位
    key: '1234567887654321'
